---
version: "3"
services:
  komfovent-ping2-json-server:
    image: rnsc/komfovent-ping2-json-server:latest
    container_name: komfovent-ping2-json-server
    ports:
      - 8080:8080
    env_file: .env
    restart: unless-stopped
  redis-komfovent-status:
    image: redis:alpine
    container_name: redis-komfovent-status
    ports:
      - 6379:6379
    restart: unless-stopped
